#!/bin/bash 
  
cd
rm -rf AUTORUN-CCMINER-JAKKARIN
git clone https://github.com/jakkarin-ba/AUTORUN-CCMINER-JAKKARIN
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/AUTORUN-CCMINER-JAKKARIN/mobile-mining/set-miner
cd
cd ../etc
rm -rf mobile-mining 
cd
cd ../bin
rm -rf add-ip edit-miner run-miner
cd
cd AUTORUN-CCMINER-JAKKARIN 
chmod +x setupdate.sh
sh setupdate.sh
